"""Generate the SNC 75-P planter authoring materials at exactly 128 x 128.

Reuses the tractor texture generator as a library (AGENTS.md rule 6: textures
complement geometry and are generated by code) and adds the two implement-only
surfaces: the canvas seed tank and the rolling ID tag plate.
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets/planter"
TEXTURE_DIR = OUT / "textures"
TEXTURE_DIR.mkdir(parents=True, exist_ok=True)

spec = importlib.util.spec_from_file_location("tractor_textures", ROOT / "tools/generate_tractor_textures.py")
tractor = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tractor)


def paint_id_plate():
    p = tractor.Painter(tractor.surface("#8d948f", 191, grain=3.0))
    p.rect((8, 8, 119, 119), "#9aa19a", "#5f6864", 2)
    for x in (16, 111):
        for y in (16, 111):
            tractor.screw(p, x, y, 2.4)
    p.rect((18, 34, 109, 58), "#1e282c", "#0f161a", 1)
    p.text((64, 47), "SNC 75-P", 15, "#e5752a", True)
    p.text((64, 72), "PLANTADEIRA", 10, "#2a3336", True)
    p.text((64, 88), "3 LINHAS", 8, "#5a6468")
    for index in range(3):
        p.rect((22 + index * 30, 98, 46 + index * 30, 112), "#c8b98f", "#8a7c55", 1)
    return p.finish()


def paint_seed_tank():
    p = tractor.Painter(tractor.surface("#dedbc2", 165, grain=3.3))
    for y in range(10, 128, 12):
        p.line((0, y, 127, y), "#cfc9ac", 1.2)
    for x in (14, 63, 113):
        p.line((x, 8, x, 119), "#c6bf9f", 1.0)
    p.rect((10, 10, 117, 40), "#d8d4ba", "#b5ae8d", 1)
    p.text((64, 28), "SNC 75-P", 11, "#e5752a", True)
    p.ellipse((46, 52, 81, 87), "#c9c2a2", "#a89f7d", 1.5)
    p.ellipse((52, 58, 75, 81), "#b3a97f", "#8d835b", 1)
    return p.finish()


def base_images():
    """The tractor's 14 surfaces, rebuilt through the shared painter functions
    (same seeds as the tractor generator) without touching the golden file."""
    m = tractor.MATERIALS
    return {
        "enamel_orange": tractor.surface(m["enamel_orange"]["color"], 101, grain=3.2),
        "enamel_dark": tractor.surface(m["enamel_dark"]["color"], 105, grain=2.8),
        "rubber": tractor.paint_rubber(),
        "tread": tractor.paint_rubber(True),
        "steel": tractor.surface(m["steel"]["color"], 119, grain=3.2, brushed=4),
        "rim": tractor.surface(m["rim"]["color"], 121, grain=2.6, brushed=1),
        "seat": tractor.paint_seat(),
        "grille": tractor.paint_grille(),
        "headlight": tractor.paint_lens("headlight", 144),
        "taillight": tractor.paint_lens("taillight", 146),
        "amber": tractor.paint_lens("amber", 147),
        "seed_tank": tractor.surface(m["seed_tank"]["color"], 150, grain=3.3),
        "decal_snc": tractor.paint_decal(),
        "gauge": tractor.paint_gauge(),
    }


def main():
    images = base_images()
    images["id_plate"] = paint_id_plate()
    images["seed_tank"] = paint_seed_tank()
    materials = dict(tractor.MATERIALS)
    materials["id_plate"] = {"color": "#8d948f", "roughness": 0.42, "metalness": 0.75}
    materials["seed_tank"] = {"color": "#dedbc2", "roughness": 0.58, "metalness": 0.05}
    manifest = {}
    for name, image in images.items():
        assert image.size == (128, 128), f"Invalid texture dimensions: {name} {image.size}"
        image.save(TEXTURE_DIR / f"{name}.png", optimize=True)
        manifest[name] = {"file": f"textures/{name}.png", **materials[name]}
    (OUT / "materials.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Generated {len(images)} planter material textures, all 128x128, in {TEXTURE_DIR}")


if __name__ == "__main__":
    main()
